In [1]:
# Import the NumPy library (https://numpy.org)
import numpy as np

In [40]:
# Create vector 
V = np.array( [[-1], [2]] )
print(V)

[[-1]
 [ 2]]


In [41]:
# Create a matrix
M = np.array( [[1,3],
               [0,2]] )
print(M)

[[1 3]
 [0 2]]


In [35]:
# M.shape = (number of lines, number of columns)
# V.shape = (number of lines, 1)
print("M.shape:", M.shape)
print("V.shape:", V.shape)

M.shape: (2, 2)
V.shape: (2, 1)


In [24]:
# Multiply a matrix and a vector (mathematical multiplication)
M @ V

array([[5],
       [4]])

In [25]:
# Multiply a matrix and a vector (element wise)
M * V

array([[-1, -3],
       [ 0,  4]])

In [26]:
# Norm of the matrix
np.linalg.norm(M)

3.7416573867739413

In [27]:
# Norm of vector
np.linalg.norm(V)

2.23606797749979

In [28]:
# Matrix transpose
M.T

array([[1, 0],
       [3, 2]])

In [38]:
# Get the determinant to check if M is invertible
np.linalg.det(M)

2.0

In [29]:
# Matrix inverse
np.linalg.inv(M)

array([[ 1. , -1.5],
       [ 0. ,  0.5]])

In [42]:
# Matrix x Matrix inverse is identity matrix
M @ np.linalg.inv(M)

array([[1., 0.],
       [0., 1.]])

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
2*np.ones(10)

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])